### ISSUE TITLE
Game crash when crafting

### ISSUE THREAD

**Issue by gobies21** [Ladysnake/Requiem#336]
most of the time my game crashes when i try to craft something when shift clicking or normal clicking.

**Comment by Pyrofab** [comment]
Could you try updating to the latest version ? It should already be fixed.

**Comment by gobies21** [comment]
im on 1.7.7 of both requiem and pandemonium and it still happens, but only when crafting not out of furnaces.

**Comment by themidget1** [comment]
it seems whenever you possess a skeleton with pandemonium and you craft it causes the bug to happen. 
and even if you unposses the skeleton and craft with something else it will still happen

**Comment by gobies21** [comment]
when it happened to me i was possessing a zombified piglin

**Comment by Pyrofab** [comment]
Could I see the crash report please ?

**Comment by Pyrofab** [comment]
Version 1.7.10 of Requiem probably doesn't fix it, but it should help me debug the issue. If one of you could send a crash report with the latest version, I would very much appreciate it.
